### ISSUE TITLE
Use "depsolver" (when it's ready) for devpi-refresh etc.

### ISSUE THREAD

**Issue by jhermann** [jhermann/rituals#22]
- https://github.com/enthought/depsolver
- Apply where applicable

**Comment by thedrow** [comment]
It doesn't look like it's ever going to be ready.

**Comment by jhermann** [comment]
The underlying devpi problem is long solved.

There are other (newer, maintained) resolvers that could be interesting to create a frozen requirements list with *just* the prod requirements → separate issue.
